version: '3.1'

services:
  flask:
    build: .
    container_name: graphqltalk
    environment:
      - DATABASE_URI=mongodb://graphqltalk-mongodb:27017/
    ports:
      - 8888:8888
    working_dir: /app
    depends_on:
      - mongo
    networks:
      - graphqltalk_net
    restart: always

  mongo:
    image: mongo
    container_name: graphqltalk-mongodb
    networks:
      - graphqltalk_net
    volumes:
      - $HOME/data/graphqltalk-mongo-data:/data/db
      - $HOME/data/graphqltalk-mongo-bkp:/data/bkp
    restart: always

networks:
  graphqltalk_net:
    driver: bridge
